### PR TITLE
Fix to not strip whitespace in `th`, `td`

### PR DESCRIPTION
**Pull request by chitoku-k**
### Initial checklist

* [x] I read the support docs 
* [x] I read the contributing guide 
* [x] I agree to follow the code of conduct 
* [x] I searched issues and couldn’t find anything (or linked relevant results below) 
* [x] If applicable, I’ve added docs and tests

### Description of changes

Since #29 rehype-react removes any whitespaces in table elements but `th` and `td` should not be its target when filtering because whitespaces are valid to appear inside them and of course React does not warn about them. This PR removes `th` and `td` from the list of target table elements and adds tests to verify they remain the same. Thanks.

### CODE REVIEW

**Comment by wooorm** [comment]
Can you show an example where this is broken?

Here’s some related reading:
* <https://github.com/facebook/react/pull/7081>
* <https://github.com/facebook/react/pull/7515>
* <https://github.com/remarkjs/remark-react/issues/64>
* <https://github.com/remarkjs/react-markdown/issues/576>

**Comment by chitoku-k** [comment]
Hi, thanks for your prompt response. I think I understood what exactly is happening.

I've made a small reproduction here:
https://github.com/chitoku-k/rehype-react-table-whitespace-test

At first check what happens with the current release:
```
npm install
npm start
```
Then apply changes in `node_modules/rehype-react/lib/index.js`, remove cache, and restart to see how it fixes the problem:
```
rm -rf node_modules/.cache
npm start
```

**Comment by wooorm** [comment]
Investigating this some more, most of why this is annoying is due to https://github.com/rehypejs/rehype-react/pull/32.

What makes it hard to investigate, is that React often does not show warnings. So it’s hard to check. But I did check, with this tree. Every commented out text is whitespace that React (including 18.2) warns about:

```js
  const tree = h("div", [
    h("p", [" ", h("span", "a"), "\n", h("span", "b."), "\t"]),
    h("table", {}, [
      // " ",
      h("thead", [
        // " ",
        h("tr", [
          // " ",
          h("th", [" ", h("span", "c"), "\n", h("span", "d."), "\t"]),
          // "\n",
          h("th", "e.")
          // "\t"
        ]),
        // "\n",
        h("tr", [])
        // "\t"
      ]),
      // "\n",
      h("tbody", [
        // " ",
        h("tr", [
          // " ",
          h("td", [" ", h("span", "f"), "\n", h("span", "g."), "\t"]),
          // "\n",
          h("td", "h.")
          // "\t"
        ]),
        // "\n",
        h("tr", [])
        // "\t"
      ]),
      // "\t",
      h("tfoot", [
        // " ",
        h("tr", [
          // " ",
          h("td", [" ", h("span", "i"), "\n", h("span", "j."), "\t"]),
          // "\n",
          h("td", "k.")
          // "\t"
        ]),
        // "\n",
        h("tr", [])
        // "\t"
      ])
    ])
  ]);
```

**Review by wooorm — APPROVED** [review]

**Comment by wooorm** [comment]
Thanks, released in [7.1.2](https://github.com/rehypejs/rehype-react/releases/tag/7.1.2)!

**Comment by chitoku-k** [comment]
Thanks for your detailed explanation and the release too!

**Pull request merged**
