### PR TITLE
types: add typescript typings

### PR DESCRIPTION
**Pull request by ChristianMurphy**
depends on https://github.com/syntax-tree/hast-to-hyperscript/pull/24

### CODE REVIEW

**Comment by wooorm** [comment]
syntax-tree/hast-to-hyperscript#24 is merged, so can you update that to 9.0.0?

**Comment by ChristianMurphy** [comment]
Updated to hast-to-hyperscript version 9 in 5e4b4bd

**Comment by wooorm** [comment]
Released, thanks!

**Pull request merged**
